### ISSUE TITLE
Could not build the application for the simulator. Error launching application on iPhone 11 Pro Max.

### ISSUE THREAD

**Issue by praveenreddyd24** [razorpay/razorpay-flutter#109]
Hi, I'm trying to integrate razorpay_flutter: ^1.2.2 while running ios build am getting an error "Could not build the application for the simulator". "Error launching the application on iPhone 11 Pro Max."  Android app is running fine but having issues with the iOS app.

**Comment by Nautiyalsachin** [comment]
Hi @praveenreddyd24, we have asked you some of the basic details which we can use for debuging your issue, right now its not giving any information from above issue that how can we fix this, please attach some more informations like -

1. Xcode version
2. razorpay-pod version
3. Errors or copy of your logs from xcode logs.

**Comment by ravitejaavv** [comment]
Hi @Nautiyalsachin 
I am also facing same issue.  Please find required details

Xcode version - 12.1
razorpay-pod version - 1.2.2
Error log:

Launching lib/main.dart on iPhone 12 Pro Max in debug mode...
Running pod install...
Running Xcode build...
Xcode build done.                                           10.6s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    /Users/ravitejaaketi/.pub-cache/hosted/pub.dartlang.org/razorpay_flutter-1.2.1/ios/Classes/RazorpayDelegate.swift:4:42: error: 'RazorpayPaymentCompletionProtocolWithData' is unavailable: cannot find Swift declaration for this protocol
    public class RazorpayDelegate: NSObject, RazorpayPaymentCompletionProtocolWithData, ExternalWalletSelectionProtocol {
                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Razorpay.RazorpayPaymentCompletionProtocolWithData:2:17: note: 'RazorpayPaymentCompletionProtocolWithData' has been explicitly marked unavailable here
    public protocol RazorpayPaymentCompletionProtocolWithData {
                    ^
    /Users/ravitejaaketi/.pub-cache/hosted/pub.dartlang.org/razorpay_flutter-1.2.1/ios/Classes/RazorpayDelegate.swift:4:85: error: 'ExternalWalletSelectionProtocol' is unavailable: cannot find Swift declaration for this protocol
    public class RazorpayDelegate: NSObject, RazorpayPaymentCompletionProtocolWithData, ExternalWalletSelectionProtocol {
                                                                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Razorpay.ExternalWalletSelectionProtocol:2:17: note: 'ExternalWalletSelectionProtocol' has been explicitly marked unavailable here
    public protocol ExternalWalletSelectionProtocol {
                    ^
    /Users/ravitejaaketi/.pub-cache/hosted/pub.dartlang.org/razorpay_flutter-1.2.1/ios/Classes/RazorpayDelegate.swift:57:24: error: cannot find 'RazorpayCheckout' in scope
            let razorpay = RazorpayCheckout.initWithKey(key ?? "", andDelegateWithData: self)
                           ^~~~~~~~~~~~~~~~
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description

**Comment by Nautiyalsachin** [comment]
Hey @ravitejaavv, can you try this [sample app](https://github.com/razorpay/razorpay-flutter/tree/master/example), and tell us if this is working for you?

**Comment by ravitejaavv** [comment]
Hi @Nautiyalsachin 

Unable to run sample app. Tried pod repo update but no luck

Xcode version - 12.1
Flutter version: 1.22.2

Error Log:

Launching lib/main.dart on iPhone 12 Pro Max in debug mode...
 
Running pod install...                                              1.0s
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Finding Podfile changes
      - Flutter
      - fluttertoast
      - razorpay_flutter

    Fetching external sources
    -> Fetching podspec for `Flutter` from `.symlinks/flutter/ios`
    -> Fetching podspec for `fluttertoast` from `.symlinks/plugins/fluttertoast/ios`
    -> Fetching podspec for `razorpay_flutter` from `.symlinks/plugins/razorpay_flutter/ios`

    Resolving dependencies of `Podfile`
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only perfomed in repo update
    [!] CocoaPods could not find compatible versions for pod "razorpay-pod":
      In snapshot (Podfile.lock):
        razorpay-pod (= 1.1.4, ~> 1.1.5)

      In Podfile:
        razorpay_flutter (from `.symlinks/plugins/razorpay_flutter/ios`) was resolved to 1.1.5, which depends on
          razorpay-pod


    You have either:
     * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
     * changed the constraints of dependency `razorpay-pod` inside your development pod `razorpay_flutter`.
       You should run `pod update razorpay-pod` to apply changes you've made.

    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:328:in `raise_error_unless_state'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:310:in `block in unwind_for_conflict'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `tap'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `unwind_for_conflict'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:257:in `process_topmost_state'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:182:in `resolve'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/resolver.rb:94:in `resolve'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/installer/analyzer.rb:1064:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/installer/analyzer.rb:1062:in `resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/installer.rb:410:in `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/installer.rb:235:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/installer.rb:234:in `resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/installer.rb:156:in `install!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/command/install.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'

Error: CocoaPods's specs repository is too out-of-date to satisfy dependencies.
To update the CocoaPods specs, run:
  pod repo update



Error running pod install
Error launching application on iPhone 12 Pro Max.

**Comment by Nautiyalsachin** [comment]
Can you try 
`pod repo update`
after that run `pod update`.

**Comment by ravitejaavv** [comment]
Hi @Nautiyalsachin 

Tried pod repo update and pod update and now I am able to run the sample app. Please find the console output. 

Ravitejas-MacBook-Pro:example ravitejaaketi$ flutter run
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Warning
──────────────────────────────────────────────────────────────────────────────
Your Flutter application is created using an older version of the Android
embedding. It's being deprecated in favor of Android embedding v2. Follow the
steps at

https://flutter.dev/go/android-project-migration

to migrate your project.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Launching lib/main.dart on iPhone 12 Pro Max in debug mode...
 
Running pod install...                                              0.9s
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Finding Podfile changes
      - Flutter
      - fluttertoast
      - razorpay_flutter

    Fetching external sources
    -> Fetching podspec for `Flutter` from `.symlinks/flutter/ios`
    -> Fetching podspec for `fluttertoast` from `.symlinks/plugins/fluttertoast/ios`
    -> Fetching podspec for `razorpay_flutter` from `.symlinks/plugins/razorpay_flutter/ios`

    Resolving dependencies of `Podfile`
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only perfomed in repo update
    [!] CocoaPods could not find compatible versions for pod "razorpay-pod":
      In snapshot (Podfile.lock):
        razorpay-pod (= 1.1.4, ~> 1.1.5)

      In Podfile:
        razorpay_flutter (from `.symlinks/plugins/razorpay_flutter/ios`) was resolved to 1.1.5, which depends on
          razorpay-pod


    You have either:
     * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
     * changed the constraints of dependency `razorpay-pod` inside your development pod `razorpay_flutter`.
       You should run `pod update razorpay-pod` to apply changes you've made.

    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:328:in `raise_error_unless_state'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:310:in `block in unwind_for_conflict'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `tap'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `unwind_for_conflict'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:257:in `process_topmost_state'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:182:in `resolve'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/resolver.rb:94:in `resolve'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/installer/analyzer.rb:1064:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/installer/analyzer.rb:1062:in `resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/installer.rb:410:in `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/installer.rb:235:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/installer.rb:234:in `resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/installer.rb:156:in `install!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/command/install.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'

Error: CocoaPods's specs repository is too out-of-date to satisfy dependencies.
To update the CocoaPods specs, run:
  pod repo update



Error running pod install
Error launching application on iPhone 12 Pro Max.
Ravitejas-MacBook-Pro:example ravitejaaketi$ pod repo update
Updating spec repo `cocoapods`
  $ /usr/bin/git -C /Users/ravitejaaketi/.cocoapods/repos/cocoapods fetch origin --progress
  remote: Enumerating objects: 516, done.        
  remote: Counting objects: 100% (516/516), done.        
  remote: Compressing objects: 100% (365/365), done.        
  remote: Total 386 (delta 248), reused 0 (delta 0), pack-reused 0        
  Receiving objects: 100% (386/386), 44.24 KiB | 8.85 MiB/s, done.
  Resolving deltas: 100% (248/248), completed with 121 local objects.
  From https://github.com/CocoaPods/Specs
     c987c7848d10..fcd4e72297ce  master     -> origin/master
  $ /usr/bin/git -C /Users/ravitejaaketi/.cocoapods/repos/cocoapods rev-parse --abbrev-ref HEAD
  master
  $ /usr/bin/git -C /Users/ravitejaaketi/.cocoapods/repos/cocoapods reset --hard origin/master
  HEAD is now at fcd4e72297ce [Add] Pushwoosh 6.0.9
Updating spec repo `trunk`

CocoaPods 1.10.0 is available.
To update use: `sudo gem install cocoapods`

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.10.0

Ravitejas-MacBook-Pro:example ravitejaaketi$ cd ios
Ravitejas-MacBook-Pro:ios ravitejaaketi$ pod update
Update all pods
Updating local specs repositories

CocoaPods 1.10.0 is available.
To update use: `sudo gem install cocoapods`

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.10.0

Analyzing dependencies
Downloading dependencies
Installing Flutter (1.0.0)
Installing fluttertoast (0.0.2)
Installing razorpay-pod (1.1.7)
Installing razorpay_flutter (1.1.5)
Generating Pods project
Integrating client project
Pod installation complete! There are 3 dependencies from the Podfile and 4 total pods installed.

[!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Runner` to `Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` or include the `Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` in your build configuration (`Flutter/Release.xcconfig`).
Ravitejas-MacBook-Pro:ios ravitejaaketi$ flutter run
Changing current working directory to: /Users/ravitejaaketi/Raviteja/SBIG/git/razorpay-flutter-master/example
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Warning
──────────────────────────────────────────────────────────────────────────────
Your Flutter application is created using an older version of the Android
embedding. It's being deprecated in favor of Android embedding v2. Follow the
steps at

https://flutter.dev/go/android-project-migration

to migrate your project.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Launching lib/main.dart on iPhone 12 Pro Max in debug mode...
 
Running pod install...                                              1.7s
Warning: Podfile is out of date
  This can cause a mismatched version of Flutter to be embedded in your app, which may result in App Store submission rejection or crashes.
  If you have local Podfile edits you would like to keep, see https://github.com/flutter/flutter/issues/24641 for instructions.
To regenerate the Podfile, run:
  rm ios/Podfile



Running Xcode build...                                                  
 └─Compiling, linking and signing...                        14.0s
Xcode build done.                                           38.7s
Waiting for iPhone 12 Pro Max to report its views...                 4ms
Syncing files to device iPhone 12 Pro Max...                       174ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h Repeat this help message.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).
An Observatory debugger and profiler on iPhone 12 Pro Max is available at: http://127.0.0.1:64758/fOyd0M6BqAY=/

**Comment by Nautiyalsachin** [comment]
@ravitejaavv Should I close this issue now then?

**Comment by ravitejaavv** [comment]
@Nautiyalsachin We can close the issue now. Thanks for the help.

**Comment by hardikvij195** [comment]
error: unable to load standard library for target 'arm64-apple-ios10.0'
/Users/hardikvij/Development/FlutterSdk/flutter/.pub-cache/hosted/pub.dartlang.org/razorpay_flutter-1.2.7/ios/Classes/RazorpayDelegate.swift:2:8: error: module compiled with Swift 5.4.2 cannot be imported by the Swift 5.5.2 compiler: /Users/hardikvij/Development/AppSynergies/MingleWiseNew/ios/Pods/razorpay-pod/Pod/Razorpay.framework/Modules/Razorpay.swiftmodule/arm64.swiftmodule
    import Razorpay
