### ISSUE TITLE
Issue with ios

### ISSUE THREAD

**Issue by sunishrai** [razorpay/razorpay-flutter#166]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
Please provide a clear and concise description of what the bug is. Include screenshots if needed.
Please test using the latest Razorpay Flutter plugin release to make sure your issue has not already been fixed: 

## Flutter Version :
2.0.5 • channel stable

## Xcode Version :
Version 12.4 (12D4e)

## Cocoapod Version :
razorpay_flutter: ^1.2.5

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Unable to install razorpay pod

## Expected Results
Describe what you expected to happen.

## Snack, code example, screenshot, or link to a repository:
    ――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

    [!] Oh no, an error occurred.

    Search for existing GitHub issues similar to yours:
    https://github.com/CocoaPods/CocoaPods/search?q=invalid+byte+sequence+in+US-ASCII&type=Issues

    If none exists, create a ticket, with the template displayed above, on:
    https://github.com/CocoaPods/CocoaPods/issues/new

    Be sure to first read the contributing guide for details on how to properly submit a ticket:
    https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

    Don't forget to anonymize any private data!

    Looking for related issues on cocoapods/cocoapods...
     - Missing install instructions for linux (install deps)
       https://github.com/CocoaPods/CocoaPods/issues/9956 [open] [2 comments]
       05 Mar 2021

     - invalid byte sequence in US-ASCII
       https://github.com/CocoaPods/CocoaPods/issues/1036 [closed] [10 comments]
       2 weeks ago

     - ArgumentError - invalid byte sequence in US-ASCII
       https://github.com/CocoaPods/CocoaPods/issues/2385 [closed] [5 comments]
       08 Sep 2020

    and 21 more at:
    https://github.com/cocoapods/cocoapods/search?q=invalid%20byte%20sequence%20in%20US-ASCII&type=Issues&utf8=✓

Error output from CocoaPods:
↳
        WARNING: CocoaPods requires your terminal to be using UTF-8 encoding.
        Consider adding the following to ~/.profile:

        export LANG=en_US.UTF-8
        

Error running pod install

**Comment by dhanrajVerma** [comment]
I am facing exactly same issue. Xcode 11.2, flutter 2.0.0 (stable), razorpay_flutter: ^1.2.5
Please fix  it as soon as possible.
@sunishrai any workaround ?

**Comment by sunishrai** [comment]
any Update.

**Comment by Nautiyalsachin** [comment]
@dhanrajVerma  @sunishrai : Can you folks please try to update the cocoapods after uninstalling and installing it again. Also as mentioned in shared logs, this issue in not caused by razorpay flutter plugin but by the cocoapods.

I also recommend you to see older close issues where merchants has fix these.

> Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=invalid+byte+sequence+in+US-ASCII&type=Issues

>If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

>Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

>Don't forget to anonymize any private data!

>Looking for related issues on cocoapods/cocoapods...
>- Missing install instructions for linux (install deps)
   https://github.com/CocoaPods/CocoaPods/issues/9956 [open] [2 comments]
   05 Mar 2021

> - invalid byte sequence in US-ASCII
   https://github.com/CocoaPods/CocoaPods/issues/1036 [closed] [10 comments]
   2 weeks ago

> - ArgumentError - invalid byte sequence in US-ASCII
   https://github.com/CocoaPods/CocoaPods/issues/2385 [closed] [5 comments]
   08 Sep 2020

>and 21 more at:
>https://github.com/cocoapods/cocoapods/search?q=invalid%20byte%20sequence%20in%20US-A
