### ISSUE TITLE
UPI app is not showing for recurring auto UPI payments 

### ISSUE THREAD

**Issue by schavanAugmont** [razorpay/razorpay-flutter#347]
When I was doing Recurring Payments Using UPI auto payment, Its not showing the installed UPI app. It only shows the text field for entering the UPI ID
Please find below screenshot for your reference.
<img width="547" alt="Screenshot 2023-10-15 105044" src="https://github.com/razorpay/razorpay-flutter/assets/136053132/aaa34d5d-6cf2-4bf8-8d65-45ab906c86b6">
![1000152750](https://github.com/razorpay/razorpay-flutter/assets/136053132/b675d2cd-31c3-45e2-b49c-991c52e7f38d)

**Comment by vivekshindhe** [comment]
Hey @schavanAugmont, thanks for reaching out. The issue here is UPI Intent recurring would not have been enabled on your merchant ID. Please raise a ticket on the Razorpay Dashboard and request for enablement. This should resolve this issue. Thank you. Closing this ticket. Please feel free to comment if the issue doesn't get resolved or open a new ticket.
