### ISSUE TITLE
Could not resolve com.razorpay:checkout:1.6.+. in Flutter Latest Version 3.24

### ISSUE THREAD

**Issue by SumitRayte** [razorpay/razorpay-flutter#404]
* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.razorpay:checkout:1.6.+.
     Required by:
         project :app > project :razorpay_flutter
      > Failed to list versions for com.razorpay:checkout.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/com/razorpay/checkout/maven-metadata.xml.
            > Could not HEAD 'https://jcenter.bintray.com/com/razorpay/checkout/maven-metadata.xml'. Received status code 500 from server: Internal Server Error

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 15s
Error: Gradle task assembleDebug failed with exit code 1

**Comment by wrteam-vimal** [comment]
Same issue here

**Comment by niladri-raychaudhuri** [comment]
Try this
https://github.com/razorpay/razorpay-flutter/issues/400#issuecomment-2285365867

**Comment by vivekshindhe** [comment]
Hey folks, the issue is not with the razorpay-checkout SDK but with mavenCentral. The razorpay-flutter package does not use jcenter. You can verify this [here](https://github.com/razorpay/razorpay-flutter/blob/b/namespace-fix-flutter/android/build.gradle). Also attaching the [link](https://status.maven.org/) to the site which states the outage in OSSRH (mavenCentral) which is why we are seeing this issue. The issue is also different for each because using a specific version has been working for some folks, while it hasn’t for others. You can try to use https://github.com/razorpay/razorpay-flutter/issues/400#issuecomment-2285365867 (Thank you @niladri-raychaudhuri for explaining the steps) fix temporarily to see if that would resolve it for you, while we look into resolving this from our end.

**Comment by vivekshindhe** [comment]
Hey folks, seems like the issue on mavenCentral is resolved. You can check the latest status [here](https://status.maven.org/). Please try to run ./gradlew --refresh-dependencies or ./gradle --refresh-dependencies or run Sync project with Gradle files in Android studio when the android project is opened.

**Comment by nimesh-devloper** [comment]
Hey folks,

I think Maven Central has resolved this issue, now just run the **flutter clean** and **flutter pub get** commands in your Terminal and it will work again.

**Comment by SumitRayte** [comment]
Okay Thank you. My issue is resolve.
